<p>I have a Ruby on Rails Website that makes HTTP calls to an external Web Service.</p>

<p>About once a day I get a SystemExit (stacktrace below) error email where a call to the service has failed.  If I then try the exact same query on my site moments later it works fine.
It's been happening since the site went live and I've had no luck tracking down what causes it.</p>

<p>Ruby is version 1.8.6 and rails is version 1.2.6.</p>

<p>Anyone else have this problem?</p>

<p>This is the error and stacktrace.</p>

<blockquote>
  <p>A SystemExit occurred
  /usr/local/lib/ruby/gems/1.8/gems/rails-1.2.6/lib/fcgi_handler.rb:116:in
  exit'
  /usr/local/lib/ruby/gems/1.8/gems/rails-1.2.6/lib/fcgi_handler.rb:116:in
  exit_now_handler'
  /usr/local/lib/ruby/gems/1.8/gems/activesupport-1.4.4/lib/active_support/inflector.rb:250:in
  to_proc' /usr/local/lib/ruby/1.8/net/protocol.rb:133:in call'
  /usr/local/lib/ruby/1.8/net/protocol.rb:133:in sysread'
  /usr/local/lib/ruby/1.8/net/protocol.rb:133:in rbuf_fill'
  /usr/local/lib/ruby/1.8/timeout.rb:56:in timeout'
  /usr/local/lib/ruby/1.8/timeout.rb:76:in timeout'
  /usr/local/lib/ruby/1.8/net/protocol.rb:132:in rbuf_fill'
  /usr/local/lib/ruby/1.8/net/protocol.rb:116:in readuntil'
  /usr/local/lib/ruby/1.8/net/protocol.rb:126:in readline'
  /usr/local/lib/ruby/1.8/net/http.rb:2017:in read_status_line'
  /usr/local/lib/ruby/1.8/net/http.rb:2006:in read_new'
  /usr/local/lib/ruby/1.8/net/http.rb:1047:in request'
  /usr/local/lib/ruby/1.8/net/http.rb:945:in request_get'
  /usr/local/lib/ruby/1.8/net/http.rb:380:in get_response'
  /usr/local/lib/ruby/1.8/net/http.rb:543:in start'
  /usr/local/lib/ruby/1.8/net/http.rb:379:in get_response'</p>
</blockquote>
